# ATC codes for products whose EMA code is incomplete, malformed or missing,
# checked by hand (user decision 2026-09-27): each against the WHOCC ATC/DDD
# Index 2026 (version 2026-01-20; the index page named), the WHOCC temporary
# list (codes for the next index, which can still change) or section 5.1 of
# the product information, where the SmPC reader missed the code. Only codes
# a second, independent check confirmed with high or medium confidence, and
# none the product already had. A code is used only where neither EMA nor
# the SmPC gives a complete code, under the rules for SmPC codes
# (complete_ema_atc_codes(), unassigned_atc_codes()). The note names the
# medicine and the WHO name of the code. A function: the URL helpers are
# defined in whocc.R, which is loaded after this file.
curated_atc_codes <- function() {
  dplyr::tribble(
    ~ema_product_number, ~atc_code, ~evidence_source, ~evidence_url, ~note,
    "EMEA/H/C/000077", "N07BC03", "whocc_index", whocc_index_url("N07BC"),
    "Orlaam: levacetylmethadol",
    "EMEA/H/C/000111", "V09HA04", "whocc_index", whocc_index_url("V09HA"),
    "LeukoScan: technetium (99mTc) sulesomab",
    "EMEA/H/C/000126", "J07CA05", "whocc_index", whocc_index_url("J07CA"),
    "Infanrix HepB: diphtheria-hepatitis B-pertussis-tetanus",
    "EMEA/H/C/000140", "V04CX05", "whocc_index", whocc_index_url("V04CX"),
    "Helicobacter Test INFAI: 13C-urea",
    "EMEA/H/C/000145", "V09IA04", "whocc_index", whocc_index_url("V09IA"),
    "HumaSPECT: technetium (99mTc) votumumab",
    "EMEA/H/C/000149", "V08DA03", "whocc_index", whocc_index_url("V08DA"),
    "EchoGen: perflenapent",
    "EMEA/H/C/000151", "V04CX05", "whocc_index", whocc_index_url("V04CX"),
    "Pylobactell: 13C-urea",
    "EMEA/H/C/000156", "J07CA07", "whocc_index", whocc_index_url("J07CA"),
    "Primavax: diphtheria-hepatitis B-tetanus",
    "EMEA/H/C/000180", "D06BB10", "whocc_index", whocc_index_url("D06BB"),
    "Zartra: imiquimod",
    "EMEA/H/C/000181", "J07AJ52", "whocc_index", whocc_index_url("J07AJ"),
    "Triacelluvax: pertussis, purified antigen, combinations with toxoids",
    "EMEA/H/C/000182", "V04CX05", "whocc_index", whocc_index_url("V04CX"),
    "Pylori-Chek: 13C-urea",
    "EMEA/H/C/000231", "J07CA08", "whocc_index", whocc_index_url("J07CA"),
    "Procomvax: haemophilus influenzae B and hepatitis B",
    "EMEA/H/C/000261", "J07BC01", "whocc_index", whocc_index_url("J07BC"),
    "Hepacare: hepatitis B, purified antigen",
    "EMEA/H/C/000298", "J07CA09", "whocc_index", whocc_index_url("J07CA"),
    paste(
      "Hexavac: diphtheria-haemophilus influenzae",
      "B-pertussis-poliomyelitis-tetanus-hepatitis B"
    ),
    "EMEA/H/C/000307", "B01AD11", "whocc_index", whocc_index_url("B01AD"),
    "Tenecteplase Boehringer Ingelheim Pharma GmbH Co. KG: tenecteplase",
    "EMEA/H/C/000327", "G04BE07", "whocc_index", whocc_index_url("G04BE"),
    "Uprima: apomorphine",
    "EMEA/H/C/000328", "G04BE07", "whocc_index", whocc_index_url("G04BE"),
    "Ixense: apomorphine",
    "EMEA/H/C/000372", "B03XA01", "whocc_index", whocc_index_url("B03XA"),
    "Dynepo: erythropoietin",
    "EMEA/H/C/000386", "G04BE07", "whocc_index", whocc_index_url("G04BE"),
    "Taluvian: apomorphine",
    "EMEA/H/C/000601", "V08CA11", "whocc_index", whocc_index_url("V08CA"),
    "Ablavar (previously Vasovist): gadofosveset",
    "EMEA/H/C/000624", "L04AG03", "whocc_index", whocc_index_url("L04AG"),
    "Natalizumab Elan Pharma: natalizumab",
    "EMEA/H/C/000769", "B06AC04", "whocc_index", whocc_index_url("B06AC"),
    "Rhucin: conestat alfa",
    "EMEA/H/C/000898", "B02BC30", "whocc_index", whocc_index_url("B02BC"),
    "Evicel: combinations",
    "EMEA/H/C/000977", "G03XC03", "whocc_index", whocc_index_url("G03XC"),
    "Fablyn: lasofoxifene",
    "EMEA/H/C/002215", "B03AC", "whocc_index", whocc_index_url("B03A"),
    "Rienso: Iron, parenteral preparations",
    "EMEA/H/C/002313", "J05AP02", "whocc_index", whocc_index_url("J05AP"),
    "Incivo: telaprevir",
    "EMEA/H/C/002332", "J05AP03", "whocc_index", whocc_index_url("J05AP"),
    "Victrelis: boceprevir",
    "EMEA/H/C/002377", "V03AE06", "whocc_index", whocc_index_url("V03AE"),
    "BindRen: colestilan",
    "EMEA/H/C/002424", "N06DA52", "whocc_index", whocc_index_url("N06DA"),
    "Acrescent: donepezil and memantine",
    "EMEA/H/C/002546", "N07XX10", "whocc_index", whocc_index_url("N07XX"),
    "Nerventra: laquinimod",
    "EMEA/H/C/002570", "V09IA08", "whocc_index", whocc_index_url("V09IA"),
    "Folcepri: technetium (99mTc) etarfolatide",
    "EMEA/H/C/002593", "M05BX53", "whocc_index", whocc_index_url("M05BX"),
    "Ditelos: strontium ranelate and colecalciferol",
    "EMEA/H/C/002600", "B03XA04", "whocc_index", whocc_index_url("B03XA"),
    "Omontys: peginesatide",
    "EMEA/H/C/002659", "L01EX06", "whocc_index", whocc_index_url("L01EX"),
    "Masiviera: masitinib",
    "EMEA/H/C/002670", "L01EX06", "whocc_index", whocc_index_url("L01EX"),
    "Masican: masitinib",
    "EMEA/H/C/002756", "M05BX53", "whocc_index", whocc_index_url("M05BX"),
    "Issarlos: strontium ranelate and colecalciferol",
    "EMEA/H/C/002772", "L03AX19", "whocc_index", whocc_index_url("L03AX"),
    "Lympreva: dasiprotimut-T",
    "EMEA/H/C/002773", "V04CX02", "whocc_index", whocc_index_url("V04CX"),
    "Neocepri: folic acid",
    "EMEA/H/C/002814", "B01AC26", "whocc_index", whocc_index_url("B01AC"),
    "Zontivity: vorapaxar",
    "EMEA/H/C/003690", "A16AX21", "whocc_index", whocc_index_url("A16AX"),
    "Skysona: elivaldogene autotemcel",
    "EMEA/H/C/003691", "B06AX02", "whocc_index", whocc_index_url("B06AX"),
    "Zynteglo: betibeglogene autotemcel",
    "EMEA/H/C/003720", "J05AP04", "whocc_index", whocc_index_url("J05AP"),
    "Faldaprevir Boehringer Ingelheim: faldaprevir",
    "EMEA/H/C/003776", "V03AE08", "whocc_index", whocc_index_url("V03AE"),
    "Fexeric: ferric citrate",
    "EMEA/H/C/003800", "H02CA03", "whocc_index", whocc_index_url("H02CA"),
    "Ketoconazole AID-SCFM: ketoconazole",
    "EMEA/H/C/003874", "L01CE03", "whocc_index", whocc_index_url("L01CE"),
    "Onzeald: etirinotecan pegol",
    "EMEA/H/C/003886", "L01FE03", "whocc_index", whocc_index_url("L01FE"),
    "Portrazza: necitumumab",
    "EMEA/H/C/003914", "B02BC30", "whocc_index", whocc_index_url("B02BC"),
    "Veraseal: combinations",
    "EMEA/H/C/004052", "L01EE03", "whocc_index", whocc_index_url("L01EE"),
    "Balimek: binimetinib",
    "EMEA/H/C/004098", "A07DA06", "whocc_index", whocc_index_url("A07DA"),
    "Truberzi: eluxadoline",
    "EMEA/H/C/004118", "L01XX53", "whocc_index", whocc_index_url("L01XX"),
    "Qinprezo: vosaroxin",
    "EMEA/H/C/004157", "H05AA04", "whocc_index", whocc_index_url("H05AA"),
    "Eladynos: abaloparatide",
    "EMEA/H/C/004165", "L04AC15", "whocc_index", whocc_index_url("L04AC"),
    "Plivensia: sirukumab",
    "EMEA/H/C/004171", "J07BX04", "whocc_index", whocc_index_url("J07BX"),
    "Dengvaxia: dengue virus vaccines",
    "EMEA/H/C/004179", "J01FA16", "whocc_index", whocc_index_url("J01FA"),
    "Solithromycin Triskel EU Services: solithromycin",
    "EMEA/H/C/004196", "A04AD14", "whocc_index", whocc_index_url("A04AD"),
    "Varuby: rolapitant",
    "EMEA/H/C/004258", "L04AX08", "whocc_index", whocc_index_url("L04AX"),
    "Alofisel: darvadstrocel",
    "EMEA/H/C/004309", "B01AF04", "whocc_index", whocc_index_url("B01AF"),
    "Dexxience: betrixaban",
    "EMEA/H/C/004354", "L01XX57", "whocc_index", whocc_index_url("L01XX"),
    "Aplidin: plitidepsin",
    "EMEA/H/C/004355", "M09AX06", "whocc_index", whocc_index_url("M09AX"),
    "Exondys: eteplirsen",
    "EMEA/H/C/004446", "B02BC30", "whocc_index", whocc_index_url("B02BC"),
    "VeraSeal: combinations",
    "EMEA/H/C/004487", "L04AJ05", "whocc_index", whocc_index_url("L04AJ"),
    "Vynpenta (previously AvacopanChemoCentryx): avacopan",
    "EMEA/H/C/004648", "N02CD02", "ema_smpc_text",
    ema_product_information_url("emgality"), "Emgality: galcanezumab",
    "EMEA/H/C/004720", "B02BX07", "whocc_index", whocc_index_url("B02BX"),
    "Mulpleo (previously Lusutrombopag Shionogi): lusutrombopag",
    "EMEA/H/C/004736", "L01XX02", "whocc_index", whocc_index_url("L01XX"),
    "Graspa: asparaginase",
    "EMEA/H/C/004829", "J01DI04", "ema_smpc_text",
    ema_product_information_url("fetcroja"), "Fetcroja: cefiderocol",
    "EMEA/H/C/004832", "L01EX15", "whocc_index", whocc_index_url("L01EX"),
    "Turalio: pexidartinib",
    "EMEA/H/C/004889", "A10BK06", "whocc_index", whocc_index_url("A10BK"),
    "Zynquista: sotagliflozin",
    "EMEA/H/C/004910", "A10BD25", "whocc_index", whocc_index_url("A10BD"),
    "Qtrilmet: metformin, saxagliptin and dapagliflozin",
    "EMEA/H/C/004938", "N07XX14", "whocc_index", whocc_index_url("N07XX"),
    "Radicava: edaravone",
    "EMEA/H/C/004961", "J05AX23", "whocc_index", whocc_index_url("J05AX"),
    "Trogarzo: ibalizumab",
    "EMEA/H/C/005102", "L01XL06", "ema_smpc_text",
    ema_product_information_url("tecartus"),
    "Tecartus: brexucabtagene autoleucel",
    "EMEA/H/C/005103", "S01LA07", "whocc_index", whocc_index_url("S01LA"),
    "Rayoqta: abicipar pegol",
    "EMEA/H/C/005189", "N02BG12", "whocc_index", whocc_index_url("N02BG"),
    "Raylumis: tanezumab",
    "EMEA/H/C/005203", "N07XX17", "whocc_index", whocc_index_url("N07XX"),
    "Miplyffa: arimoclomol",
    "EMEA/H/C/005205", "N01BB59", "whocc_index", whocc_index_url("N01BB"),
    "Zynrelef: bupivacaine and meloxicam",
    "EMEA/H/C/005247", "L04AJ13", "whocc_temporary", whocc_temporary_url,
    "Yartemlea: narsoplimab",
    "EMEA/H/C/005287", "N02CD05", "ema_smpc_text",
    ema_product_information_url("vyepti"), "Vyepti: eptinezumab",
    "EMEA/H/C/005308", "N04CX01", "whocc_index", whocc_index_url("N04CX"),
    "Nouryant: istradefylline",
    "EMEA/H/C/005322", "L01FB02", "whocc_index", whocc_index_url("L01FB"),
    "Lumoxiti: moxetumomab pasudotox",
    "EMEA/H/C/005337", "J07BX02", "whocc_index", whocc_index_url("J07BX"),
    "Zabdeno: ebola vaccines",
    "EMEA/H/C/005343", "J07BX02", "whocc_index", whocc_index_url("J07BX"),
    "Mvabea: ebola vaccines",
    "EMEA/H/C/005361", "L01EN03", "whocc_index", whocc_index_url("L01EN"),
    "Febseltiq: infigratinib",
    "EMEA/H/C/005499", "V10XA03", "whocc_index", whocc_index_url("V10XA"),
    "Omblastys: iodine (131I) omburtamab",
    "EMEA/H/C/005523", "L04AJ05", "whocc_index", whocc_index_url("L04AJ"),
    "Tavneos: avacopan",
    "EMEA/H/C/005551", "A05AX04", "whocc_index", whocc_index_url("A05AX"),
    "Livmarli: maralixibat chloride",
    "EMEA/H/C/005558", "N06DX03", "whocc_index", whocc_index_url("N06DX"),
    "Aduhelm: aducanumab",
    "EMEA/H/C/005621", "L01EB10", "whocc_index", whocc_index_url("L01EB"),
    "Exkivity: mobocertinib",
    "EMEA/H/C/005651", "L01XY04", "whocc_index", whocc_index_url("L01XY"),
    "Nidlegy: bifikafusp alfa and onfekafusp alfa",
    "EMEA/H/C/005682", "J02AC06", "whocc_index", whocc_index_url("J02AC"),
    "Vivjoa: oteseconazole",
    "EMEA/H/C/005703", "A16AB23", "whocc_index", whocc_index_url("A16AB"),
    "Pombiliti: cipaglucosidase alfa",
    "EMEA/H/C/005746", "B03XA07", "whocc_index", whocc_index_url("B03XA"),
    "Jesduvroq: daprodustat",
    "EMEA/H/C/005789", "J05AB18", "whocc_index", whocc_index_url("J05AB"),
    "Lagevrio: molnupiravir",
    "EMEA/H/C/005820", "R03DX13", "whocc_temporary", whocc_temporary_url,
    "Brinsupri: brensocatib",
    "EMEA/H/C/005855", "A16AX26", "whocc_index", whocc_index_url("A16AX"),
    "Zeydovio: glepaglutide",
    "EMEA/H/C/005901", "N07XX19", "whocc_index", whocc_index_url("N07XX"),
    "Albrioza: sodium phenylbutyrate and ursodoxicoltaurine",
    "EMEA/H/C/005909", "M09AX16", "whocc_index", whocc_index_url("M09AX"),
    "Isembyld: apitegromab",
    "EMEA/H/C/006068", "N07XX23", "whocc_index", whocc_index_url("N07XX"),
    "Dazluma: troriluzole",
    "EMEA/H/C/006177", "V04CF02", "whocc_index", whocc_index_url("V04CF"),
    "Siiltibcy: mycobacterium tuberculosis, recombinant antigens",
    "EMEA/H/C/006184", "L02BA06", "whocc_temporary", whocc_temporary_url,
    "Inluriyo: imlunestrant",
    "EMEA/H/C/006241", "A05AX08", "whocc_index", whocc_index_url("A05AX"),
    "Lynavoy: linerixibat",
    "EMEA/H/C/006259", "L01XH07", "whocc_index", whocc_index_url("L01XH"),
    "Kinselby: resminostat",
    "EMEA/H/C/006261", "N07XX26", "whocc_index", whocc_index_url("N07XX"),
    "Nurzigma: pridopidine",
    "EMEA/H/C/006317", "L01EX33", "whocc_temporary", whocc_temporary_url,
    "Qezzaqar: catequentinib",
    "EMEA/H/C/006370", "L01FX37", "whocc_index", whocc_index_url("L01FX"),
    "Lynozyfic: linvoseltamab",
    "EMEA/H/C/006475", "N06DX06", "whocc_index", whocc_index_url("N06DX"),
    "Blarcamesine Anavex: blarcamesine",
    "EMEA/H/C/006477", "C10AX21", "whocc_temporary", whocc_temporary_url,
    "Tryngolza: olezarsen",
    "EMEA/H/C/006516", "C10AX22", "whocc_temporary", whocc_temporary_url,
    "Ubeslo: obicetrapib",
    "EMEA/H/C/006517", "C10BA17", "whocc_temporary", whocc_temporary_url,
    "Evlarco: obicetrapib and ezetimibe",
    "EMEA/H/C/006525", "B06AX09", "whocc_temporary", whocc_temporary_url,
    "Waskyra: etuvetidigene autotemcel",
    "EMEA/H/C/006554", "B06AC09", "ema_smpc_text",
    ema_product_information_url("dawnzera"), "Dawnzera: donidalorsen",
    "EMEA/H/C/006579", "C10AX20", "whocc_temporary", whocc_temporary_url,
    "Redemplo: plozasiran",
    "EMEA/H/C/006641", "L01FF16", "whocc_index", whocc_index_url("L01FF"),
    "Zumrad: sasanlimab",
    "EMEA/H/C/006694", "C10AX19", "whocc_index", whocc_index_url("C10AX"),
    "Lyrokaul: lerodalcibep",
    "EMEA/H/C/006742", "R03BX02", "whocc_index", whocc_index_url("R03BX"),
    "Ohtuvayre: ensifentrine"
  ) |>
    dplyr::mutate(checked_date = as.Date("2026-09-27"), .before = "note")
}

empty_curated_atc_codes <- function() {
  dplyr::tibble(
    ema_product_number = character(),
    atc_code = character(),
    evidence_source = character(),
    evidence_url = character(),
    checked_date = as.Date(character()),
    note = character()
  )
}

ema_product_information_url <- function(slug) {
  paste0(
    "https://www.ema.europa.eu/en/documents/product-information/",
    slug,
    "-epar-product-information_en.pdf"
  )
}
