# Curated company data (user decisions 2026-09-28). A group is the operating
# company people know (not a family holding, private-equity vehicle or state
# agency: GLEIF's literal ultimate parent is kept as provenance), as of
# `curated_companies_as_of`: current owner only. Joint ventures are their own
# group, with the partner groups listed. Holders are named as EMA or the
# Union Register spell them; every holder that folds to the same company
# (company_match_key()) follows.
curated_companies_as_of <- as.Date("2026-09-28")

curated_company_data <- function() {
  list(
    groups = curated_company_groups(),
    members = curated_group_members(),
    aliases = curated_company_aliases(),
    representatives = curated_representatives(),
    sponsors = curated_medicine_sponsors(),
    as_of = curated_companies_as_of
  )
}

# lei: the operating company's LEI; gleif_ultimate_parent(_lei): GLEIF's
# ultimate parent where it differs (a holding). Partners: group keys,
# separated by ";".
curated_company_groups <- function() {
  dplyr::tribble(
    ~group_key, ~name, ~monogram, ~lei, ~gleif_legal_name,
    ~gleif_ultimate_parent_lei, ~gleif_ultimate_parent, ~partners,
    "g.novartis", "Novartis", "NVS", "5493007HIVTX6SY6XD66", "NOVARTIS AG",
    NA, NA, NA,
    "g.sandoz", "Sandoz", "SDZ", NA, NA, NA, NA, NA,
    "g.pfizer", "Pfizer", "PFE", "765LHXWGK1KXCLTFYQ30", "PFIZER INC.",
    NA, NA, NA,
    "g.intas", "Intas (Accord Healthcare)", "INT", "335800BL323XQZHTQA07",
    "INTAS PHARMACEUTICALS LIMITED", NA, NA, NA,
    "g.msd", "MSD (Merck & Co.)", "MSD", "4YV9Y5M8S0BRK1RP0397",
    "MERCK & CO., INC.", NA, NA, NA,
    "g.teva", "Teva", "TEV", "549300BAFGM4RC74ZJ94",
    "TEVA PHARMACEUTICAL INDUSTRIES LIMITED", NA, NA, NA,
    "g.johnson-johnson", "Johnson & Johnson", "JNJ", "549300G0CFPGEF6X2043",
    "Johnson & Johnson", NA, NA, NA,
    "g.astrazeneca", "AstraZeneca", "AZ", "PY6ZZQWO2IZFZC3IOL08",
    "ASTRAZENECA PLC", NA, NA, NA,
    "g.roche", "Roche", "RO", "549300U41AUUVOAAOB37", "Roche Holding AG",
    NA, NA, NA,
    "g.sanofi", "Sanofi", "SNY", "549300E9PC51EN656011", "SANOFI",
    NA, NA, NA,
    "g.eli-lilly", "Eli Lilly", "LLY", "FRDRIPF3EKNDJ2CQJL29",
    "ELI LILLY AND COMPANY", NA, NA, NA,
    "g.viatris", "Viatris", "VTR", "254900ZZTSW7NL773X71", "VIATRIS INC.",
    NA, NA, NA,
    "g.bristol-myers-squibb", "Bristol Myers Squibb", "BMS",
    "HLYYNH7UQUORYSJQCN42", "BRISTOL-MYERS SQUIBB COMPANY", NA, NA, NA,
    "g.novo-nordisk", "Novo Nordisk", "NN", "549300DAQ1CVT6CXN342",
    "NOVO NORDISK A/S", NA, NA, NA,
    "g.krka", "Krka", "KRK", "549300H9RLRTRTLRUZ73",
    "KRKA, tovarna zdravil, d.d., Novo mesto", NA, NA, NA,
    "g.gilead", "Gilead", "GIL", "549300WTZWR07K8MNV44",
    "GILEAD SCIENCES, INC.", NA, NA, NA,
    "g.bayer", "Bayer", "BAY", "549300J4U55H3WP1XT59",
    "Bayer Aktiengesellschaft", NA, NA, NA,
    "g.gsk", "GSK", "GSK", "5493000HZTVUYLO1D793", "GSK PLC", NA, NA, NA,
    "g.boehringer-ingelheim", "Boehringer Ingelheim", "BI",
    "529900UYZPE4QQMRRE87", "Boehringer Ingelheim International GmbH",
    "529900P5FAANZASUYL28", "C.H. Boehringer Sohn AG & Co. KG", NA,
    "g.amgen", "Amgen", "AMG", "62QBXGPJ34PQ72Z12S66", "AMGEN INC.",
    NA, NA, NA,
    "g.abbvie", "AbbVie", "ABV", "FR5LCKFTG8054YNNRU85", "ABBVIE INC.",
    NA, NA, NA,
    "g.gedeon-richter", "Gedeon Richter", "GR", NA, NA, NA, NA, NA,
    "g.stada", "STADA", "STA", "529900FMTTLMH0P0DL10",
    "STADA Arzneimittel Aktiengesellschaft", "3912004KLYMNXGEH1855",
    "Nidda German Topco GmbH", NA,
    "g.zentiva", "Zentiva", "ZEN", NA, NA, NA, NA, NA,
    "g.celltrion", "Celltrion", "CEL", NA, NA, NA, NA, NA,
    "g.ucb", "UCB", "UCB", "2138008J191VLSGY5A09", "U C B", NA, NA, NA,
    "g.servier", "Servier", "SRV", "969500Y8PG1HQ9Y6NA31",
    "LES LABORATOIRES SERVIER", NA, NA, NA,
    "g.sun-pharma", "Sun Pharma", "SUN", "335800KJ7GE29LB4SS73",
    "SUN PHARMACEUTICAL INDUSTRIES LIMITED", NA, NA, NA,
    "g.chiesi", "Chiesi", "CHI", "8156009817CA59AD8106",
    "CHIESI FARMACEUTICI S.P.A.", "815600A07AD23F71D845", "VALLINE S.R.L.",
    NA,
    "g.takeda", "Takeda", "TAK", "549300ZLMVP4X0OGR454",
    "Takeda Pharmaceutical Company Limited", NA, NA, NA,
    "g.biocon", "Biocon Biologics", "BCB", NA, NA, NA, NA, NA,
    "g.astellas", "Astellas", "AST", "529900IB708DY2HBBB35",
    "Astellas Pharma Inc.", NA, NA, NA,
    "g.fresenius", "Fresenius", "FRE", "XDFJ0CYCOO1FXRFTQS51",
    "Fresenius SE & Co. KGaA", NA, NA, NA,
    "g.samsung-bioepis", "Samsung Bioepis", "SB", NA, NA, NA, NA, NA,
    "g.merck-kgaa", "Merck KGaA", "MKG", NA, NA, NA, NA, NA,
    "g.organon", "Organon", "OGN", "549300AMCKY57OK2CO56", "ORGANON & CO.",
    NA, NA, NA,
    "g.sobi", "Sobi", "SBI", "549300124Y3MQI87PT35",
    "Swedish Orphan Biovitrum AB (publ)", NA, NA, NA,
    "g.csl", "CSL", "CSL", "529900ECSECK5ZDQTE14", "CSL LIMITED",
    NA, NA, NA,
    "g.recordati", "Recordati", "REC", "815600FBF92FD3531704",
    paste(
      "RECORDATI INDUSTRIA CHIMICA E FARMACEUTICA S.P.A. IN BREVE",
      "RECORDATI S.P.A."
    ),
    NA, NA, NA,
    "g.pierre-fabre", "Pierre Fabre", "PF", "969500ROQWSNEW8T9489",
    "PIERRE FABRE MEDICAMENT", "969500N6YMBRQ1GZKJ27",
    "PIERRE FABRE PARTICIPATIONS", NA,
    "g.medac", "medac", "MDC", "529900CYHUGUOZJN0I17",
    "Medac Gesellschaft für klinische Spezialpräparate m.b.H.",
    NA, NA, NA,
    "g.biogen", "Biogen", "BGN", "W8J5WZB5IY3K0NDQT671", "BIOGEN INC.",
    NA, NA, NA,
    "g.otsuka", "Otsuka", "OTS", NA, NA, NA, NA, NA,
    "g.advanz", "Advanz Pharma", "ADV", NA, NA, NA, NA, NA,
    "g.biomarin", "BioMarin", "BMN", "NSLL8ITTRR0J5HEMR848",
    "BIOMARIN PHARMACEUTICAL INC.", NA, NA, NA,
    "g.neuraxpharm", "Neuraxpharm", "NXP", "959800C6U9VUWDQL8408",
    "NEURAXPHARM PHARMACEUTICALS S.L.(SOCIEDAD UNIPERSONAL)", NA, NA, NA,
    "g.daiichi-sankyo", "Daiichi Sankyo", "DS", "353800XGIU2IHQGC9504",
    "Daiichi Sankyo Co., Ltd.", NA, NA, NA,
    "g.orion", "Orion", "ORN", "74370029VAHCXDR7B745", "Orion Oyj",
    NA, NA, NA,
    "g.cheplapharm", "Cheplapharm", "CHP", "529900ONXKBELT7EW052",
    "Cheplapharm Arzneimittel GmbH", "529900GBPA5Q6JIBEO60",
    "Braun Invest Holding GmbH", NA,
    "g.ipsen", "Ipsen", "IPS", "549300M6SGDPB4Z94P11", "IPSEN", NA, NA, NA,
    "g.esteve", "Esteve", "EST", "95980020140005174448",
    "ESTEVE PHARMACEUTICALS S.A.", "959800YD5H9DYP7YT664",
    "ESTEVE HEALTHCARE S.L.", NA,
    "g.incyte", "Incyte", "INC", NA, NA, NA, NA, NA,
    "g.curium", "Curium", "CUR", NA, NA, NA, NA, NA,
    "g.menarini", "Menarini", "MEN", "8156002DC6B01873B624",
    "A. MENARINI - INDUSTRIE FARMACEUTICHE RIUNITE - S.R.L.", NA, NA, NA,
    "g.kyowa-kirin", "Kyowa Kirin", "KK", NA, NA, NA, NA, NA,
    "g.abbott", "Abbott", "ABT", "HQD377W2YR662HK5JX27",
    "ABBOTT LABORATORIES", NA, NA, NA,
    "g.vertex", "Vertex", "VRT", NA, NA, NA, NA, NA,
    "g.almirall", "Almirall", "ALM", "95980020140005007996", "ALMIRALL S.A.",
    NA, NA, NA,
    "g.lundbeck", "Lundbeck", "LUN", "5493006R4KC2OI5D3470",
    "H. LUNDBECK A/S", "254900JH964PYU6MC463", "LUNDBECKFONDEN", NA,
    "g.leo-pharma", "LEO Pharma", "LEO", "52990077KVK7QCK2NG31",
    "LEO Pharma A/S", NA, NA, NA,
    "g.grunenthal", "Grünenthal", "GRT", "529900SH895E31PGLA72",
    "Grünenthal GmbH", NA, NA, NA,
    "g.theramex", "Theramex", "TMX", NA, NA, NA, NA, NA,
    "g.eisai", "Eisai", "EIS", NA, NA, NA, NA, NA,
    "g.jazz", "Jazz Pharmaceuticals", "JAZ", "635400GAUMJCLEZRRV50",
    "Jazz Pharmaceuticals Public Limited Company", NA, NA, NA,
    "g.dr-reddys", "Dr. Reddy's", "RDY", NA, NA, NA, NA, NA,
    "g.perrigo", "Perrigo", "PRG", NA, NA, NA, NA, NA,
    "g.glenmark", "Glenmark", "GMK", "335800WKECZXIIT9GK20",
    "GLENMARK PHARMACEUTICALS LIMITED", NA, NA, NA,
    "g.merz", "Merz", "MRZ", NA, NA, NA, NA, NA,
    "g.acino", "Acino", "ACI", NA, NA, NA, NA, NA,
    "g.dompe", "Dompé", "DOM", "81560052D172F2DBC326",
    "DOMPE' FARMACEUTICI - S.P.A.", "815600E2AFF2628FE804",
    "DOMPE' HOLDINGS SRL", NA,
    "g.bracco", "Bracco", "BRC", "529900P0D461YTTYPQ07",
    "BRACCO IMAGING S.P.A.", "549300IPJJS0DK6UEY77", "BRACCO S.P.A.", NA,
    "g.cosmo", "Cosmo Pharmaceuticals", "COS", "724500OX0EBQRYTVV639",
    "COSMO Pharmaceuticals N.V.", NA, NA, NA,
    "g.pharming", "Pharming", "PHR", "724500DCJ9MPG74JEH91",
    "Pharming Group N.V.", NA, NA, NA,
    "g.bristol-myers-squibb-pfizer",
    "Bristol Myers Squibb and Pfizer (joint venture)", "BPF", NA, NA, NA, NA,
    "g.bristol-myers-squibb;g.pfizer",
    "g.sanofi-bristol-myers-squibb",
    "Sanofi and Bristol Myers Squibb (joint venture)", "SBM", NA, NA, NA,
    NA, "g.bristol-myers-squibb;g.sanofi",
    "g.sanofi-pasteur-msd", "Sanofi Pasteur MSD (joint venture)", "SPM",
    NA, NA, NA, NA, "g.msd;g.sanofi",
    "g.mcm-vaccine", "MCM Vaccine (joint venture)", "MCM", NA, NA, NA, NA,
    "g.msd;g.sanofi",
    "g.vifor-fresenius-medical-care",
    "Vifor Fresenius Medical Care Renal Pharma (joint venture)", "VFM", NA,
    NA, NA, NA, "g.csl"
  ) |>
    dplyr::mutate(
      other_partners = unname(curated_other_partners[.data$group_key]),
      joint_venture = !is.na(.data$partners) | !is.na(.data$other_partners),
      .before = "partners"
    ) |>
    dplyr::relocate("other_partners", .after = "partners")
}

# Joint-venture partners that are no group in the data, by name.
curated_other_partners <- c(
  "g.vifor-fresenius-medical-care" = "Fresenius Medical Care"
)

# Holders in a group; for ownership changes a note and its evidence.
curated_group_members <- function() {
  wikipedia <- function(title) paste0("https://en.wikipedia.org/wiki/", title)
  dplyr::tribble(
    ~group_key, ~holder, ~note, ~evidence_url,
    "g.novartis", "Novartis Europharm Limited", NA, NA,
    "g.novartis", "Novartis", NA, NA,
    "g.novartis", "Novartis Ophthalmics Europe Ltd.", NA, NA,
    "g.sandoz", "Sandoz GmbH", "Spun off from Novartis in 2023",
    wikipedia("Sandoz"),
    "g.sandoz", "Sandoz Pharmaceuticals d.d.",
    "Spun off from Novartis in 2023", wikipedia("Sandoz"),
    "g.sandoz", "Hexal AG", "Acquired by Sandoz in 2005",
    wikipedia("Sandoz"),
    "g.sandoz", "1 A Pharma GmbH", "A Sandoz brand",
    "https://www.sandoz.com/de-de/unsere-marken/1-pharma/",
    "g.pfizer", "Pfizer Europe MA EEIG", NA, NA,
    "g.pfizer", "Pfizer Ireland Pharmaceuticals", NA, NA,
    "g.pfizer", "Roerig Farmaceutici Italiana S.p.A.",
    "Merged into Pfizer Italiana in 2000",
    "https://www.gazzettaufficiale.it/eli/id/2000/01/24/S-654/p2",
    "g.pfizer", "Wyeth Europa Ltd", "Wyeth acquired by Pfizer in 2009",
    wikipedia("Wyeth"),
    "g.pfizer", "Wyeth Lederle Vaccines S.A.",
    "Wyeth acquired by Pfizer in 2009", wikipedia("Wyeth"),
    "g.pfizer", "Pharmacia Europe EEIG",
    paste(
      "Pharmacia merged into Pfizer in 2003 (so Pharmacia - Pfizer EEIG,",
      "the two companies' joint EEIG, is Pfizer's alone: Bextra, whose",
      "holder the Union Register names Pharmacia Europe EEIG)"
    ),
    wikipedia("Pfizer"),
    "g.pfizer", "Hospira UK Limited", "Hospira acquired by Pfizer in 2015",
    wikipedia("Hospira"),
    "g.pfizer", "Arena Pharmaceutical Enterprises Limited",
    "Arena acquired by Pfizer in 2022",
    paste0(
      "https://www.pfizer.com/news/press-release/press-release-detail/",
      "pfizer-completes-acquisition-arena-pharmaceuticals"
    ),
    "g.intas", "Accord Healthcare S.L.U.",
    paste(
      "Intas Pharmaceuticals' company (GLEIF: the ultimate parent of",
      "Accord Healthcare Limited)"
    ),
    "https://search.gleif.org/#/record/213800S19K36OUQLB824",
    "g.intas", "Intas Third Party Sales 2005 S.L.", NA, NA,
    "g.msd", "Merck Sharp & Dohme B.V.", NA, NA,
    "g.msd", "Schering-Plough Europe",
    "Schering-Plough merged with Merck & Co. in 2009",
    wikipedia("Schering-Plough"),
    "g.msd", "SP Europe", "Schering-Plough merged with Merck & Co. in 2009",
    wikipedia("Schering-Plough"),
    "g.teva", "Teva B.V.", NA, NA,
    "g.teva", "Teva Pharma B.V.", NA, NA,
    "g.teva", "Teva Generics B.V", NA, NA,
    "g.teva", "ratiopharm GmbH", "ratiopharm acquired by Teva in 2010",
    wikipedia("Ratiopharm"),
    "g.teva", "AbZ-Pharma GmbH", "A Teva brand in Germany (with ratiopharm)",
    "https://www.teva.de/teva-weltweit/teva-in-deutschland.html",
    "g.teva", "Actavis Group PTC ehf",
    "Actavis generics business acquired by Teva in 2016",
    wikipedia("Allergan"),
    "g.teva", "Norton Healthcare Ltd.",
    "IVAX's UK company; Teva acquired IVAX in 2006",
    paste0(
      "https://ir.tevapharm.com/news-and-events/press-releases/",
      "press-release-details/2006/Teva-Completes-Acquisition-of-Ivax/",
      "default.aspx"
    ),
    "g.johnson-johnson", "Janssen-Cilag International NV", NA, NA,
    "g.johnson-johnson", "Centocor B.V.",
    "Centocor (now Janssen Biotech) acquired by J&J in 1999",
    wikipedia("Janssen_Biotech"),
    "g.johnson-johnson", "Omrix Biopharmaceuticals N. V.",
    "Omrix acquired by J&J in 2008",
    paste0(
      "https://johnsonandjohnson.gcs-web.com/news-releases/",
      "news-release-details/johnson-johnson-completes-acquisition-omrix-",
      "biopharmaceuticals/"
    ),
    "g.astrazeneca", "AstraZeneca AB", NA, NA,
    "g.astrazeneca", "Alexion Europe SAS",
    "Alexion acquired by AstraZeneca in 2021",
    wikipedia("Alexion_Pharmaceuticals"),
    "g.astrazeneca", "MedImmune LLC",
    "MedImmune acquired by AstraZeneca in 2007", wikipedia("MedImmune"),
    "g.roche", "Roche Registration GmbH", NA, NA,
    "g.sanofi", "Sanofi Winthrop Industrie", NA, NA,
    "g.sanofi", "Sanofi B.V.", NA, NA,
    "g.sanofi", "sanofi-aventis groupe", NA, NA,
    "g.sanofi", "Aventis Pharma S.A.", "Aventis acquired by Sanofi in 2004",
    wikipedia("Aventis"),
    "g.sanofi", "Genzyme Europe B.V.", "Genzyme acquired by Sanofi in 2011",
    wikipedia("Genzyme"),
    "g.sanofi", "Sanofi Pasteur", NA, NA,
    "g.sanofi", "Ablynx NV", "Ablynx acquired by Sanofi in 2018",
    wikipedia("Ablynx"),
    "g.eli-lilly", "Eli Lilly Nederland B.V.", NA, NA,
    "g.viatris", "Viatris Limited", NA, NA,
    "g.viatris", "Viatris Healthcare Limited", NA, NA,
    "g.viatris", "Mylan Pharmaceuticals Limited",
    "Mylan combined with Upjohn into Viatris in 2020", wikipedia("Viatris"),
    "g.viatris", "Mylan S.A.S.",
    "Mylan combined with Upjohn into Viatris in 2020", wikipedia("Viatris"),
    "g.viatris", "Mylan IRE Healthcare Limited",
    "Mylan combined with Upjohn into Viatris in 2020", wikipedia("Viatris"),
    "g.viatris", "Mylan dura GmbH",
    "Mylan combined with Upjohn into Viatris in 2020", wikipedia("Viatris"),
    "g.viatris", "Meda AB", "Meda acquired by Mylan in 2016",
    wikipedia("Viatris"),
    "g.viatris", "Generics (UK) Limited",
    "Merck KGaA's generics business acquired by Mylan in 2007",
    paste0(
      "https://investor.mylan.com/news-releases/news-release-details/",
      "mylan-completes-acquisition-generics-business-merck-kgaa"
    ),
    "g.viatris", "Upjohn EESV",
    "Pfizer's Upjohn combined with Mylan into Viatris in 2020",
    wikipedia("Viatris"),
    "g.bristol-myers-squibb", "Bristol-Myers Squibb Pharma EEIG", NA, NA,
    "g.bristol-myers-squibb", "Celgene Europe BV",
    "Celgene acquired by Bristol Myers Squibb in 2019", wikipedia("Celgene"),
    "g.bristol-myers-squibb", "Pharmion Ltd.",
    "Pharmion acquired by Celgene in 2008 (Bristol Myers Squibb since 2019)",
    wikipedia("Celgene"),
    "g.novo-nordisk", "Novo Nordisk A/S", NA, NA,
    "g.krka", "Krka, d.d., Novo mesto", NA, NA,
    "g.krka", "Tad Pharma GmbH", "Acquired by Krka in 2007",
    paste0(
      "https://www.krka.biz/about-us/international-presence/",
      "krka-around-the-world/tad-pharma/"
    ),
    "g.gilead", "Gilead Sciences Ireland UC", NA, NA,
    "g.gilead", "Kite Pharma EU B.V.", "Kite acquired by Gilead in 2017",
    wikipedia("Kite_Pharma"),
    "g.gilead", "Immunomedics GmbH",
    "Immunomedics acquired by Gilead in 2020", wikipedia("Immunomedics"),
    "g.bayer", "Bayer AG", NA, NA,
    "g.bayer", "Bayer Schering Pharma AG", NA, NA,
    "g.gsk", "GlaxoSmithKline Trading Services Limited", NA, NA,
    "g.gsk", "GlaxoSmithKline Biologicals S.A.", NA, NA,
    "g.gsk", "Glaxo Group Ltd.", NA, NA,
    "g.gsk", "SmithKline Beecham Plc", NA, NA,
    "g.gsk", "Beecham Group plc", NA, NA,
    "g.gsk", "GSK Vaccines S.r.l.", NA, NA,
    "g.gsk", "GlaxoSmithKline Vaccines S.r.l.", NA, NA,
    "g.gsk", "Chiron S.p.A.",
    "Chiron acquired by Novartis in 2006; its vaccines went to GSK in 2015",
    wikipedia("Chiron_Corporation"),
    "g.gsk", "ViiV Healthcare B.V.",
    paste(
      "Majority-owned by GSK (78.3%), with Shionogi (21.7%) since Pfizer",
      "left in March 2026"
    ),
    "https://www.shionogi.com/global/en/news/2026/04/20260401_12.html",
    "g.gsk", "TESARO Bio Netherlands B.V.", "Tesaro acquired by GSK in 2019",
    wikipedia("Tesaro"),
    "g.boehringer-ingelheim", "Boehringer Ingelheim International GmbH",
    NA, NA,
    "g.boehringer-ingelheim", "Dr. Karl Thomae GmbH",
    "Acquired by Boehringer Ingelheim in 1928",
    paste0(
      "https://www.boehringer-ingelheim.com/about-us/history/",
      "1885-1948-innovative-beginnings"
    ),
    "g.amgen", "Amgen Europe B.V.", NA, NA,
    "g.amgen", "Amgen Technology (Ireland) UC", NA, NA,
    "g.amgen", "ChemoCentryx Ltd", "ChemoCentryx acquired by Amgen in 2022",
    paste0(
      "https://www.amgen.com/newsroom/press-releases/2022/10/",
      "amgen-successfully-completes-acquisition-of-chemocentryx"
    ),
    "g.abbvie", "AbbVie Deutschland GmbH & Co. KG", NA, NA,
    "g.abbvie", "Allergan Pharmaceuticals International Limited",
    "Allergan acquired by AbbVie in 2020", wikipedia("Allergan"),
    "g.abbvie", "Warner Chilcott UK Ltd.",
    paste(
      "Warner Chilcott acquired by Actavis (renamed Allergan) in 2013;",
      "AbbVie since 2020"
    ),
    wikipedia("Allergan"),
    "g.gedeon-richter", "Gedeon Richter Plc.", NA, NA,
    "g.stada", "STADA Arzneimittel AG", NA, NA,
    "g.zentiva", "Zentiva k.s.", NA, NA,
    "g.celltrion", "Celltrion Healthcare Hungary Kft.", NA, NA,
    "g.ucb", "UCB Pharma S.A.", NA, NA,
    "g.servier", "Les Laboratoires Servier", NA, NA,
    "g.servier", "Servier (Ireland) Industries Ltd", NA, NA,
    "g.sun-pharma", "Sun Pharmaceutical Industries Europe B.V.", NA, NA,
    "g.chiesi", "Chiesi Farmaceutici S.p.A.", NA, NA,
    "g.chiesi", "Amryt Pharmaceuticals DAC",
    "Amryt acquired by Chiesi in 2023",
    paste0(
      "https://www.nasdaq.com/press-release/",
      "chiesi-farmaceutici-s.p.a.-completes-acquisition-of-amryt-pharma-plc-",
      "2023-04-12"
    ),
    "g.chiesi", "Amryt AG", "Amryt acquired by Chiesi in 2023",
    paste0(
      "https://www.nasdaq.com/press-release/",
      "chiesi-farmaceutici-s.p.a.-completes-acquisition-of-amryt-pharma-plc-",
      "2023-04-12"
    ),
    "g.takeda", "Takeda Pharma A/S", NA, NA,
    "g.takeda", "Takeda Pharmaceuticals International AG", NA, NA,
    "g.takeda", "Takeda GmbH", NA, NA,
    "g.takeda", "Takeda Global Research and Development Centre (Europe)",
    NA, NA,
    "g.takeda", "Baxalta Innovations GmbH",
    "Baxalta acquired by Shire in 2016, Shire by Takeda in 2019",
    wikipedia("Shire_(pharmaceutical_company)"),
    "g.takeda", "Shire Pharmaceutical Contracts Limited",
    "Shire acquired by Takeda in 2019",
    wikipedia("Shire_(pharmaceutical_company)"),
    "g.takeda", "NPS Pharma Holdings Limited",
    "NPS acquired by Shire in 2015 (Takeda since 2019)",
    wikipedia("Shire_(pharmaceutical_company)"),
    "g.takeda", "TiGenix N.V.", "TiGenix acquired by Takeda in 2018",
    wikipedia("TiGenix"),
    "g.takeda", "Dyax s.a.", "Dyax acquired by Shire (Takeda since 2019)",
    wikipedia("Shire_(pharmaceutical_company)"),
    "g.biocon", "Biocon Biologics Ireland Limited", NA, NA,
    "g.biocon", "Biosimilar Collaborations Ireland Limited",
    "Viatris's biosimilars business acquired by Biocon Biologics in 2022",
    wikipedia("Viatris"),
    "g.astellas", "Astellas Pharma Europe B.V.", NA, NA,
    "g.fresenius", "Fresenius Kabi Deutschland GmbH", NA, NA,
    "g.fresenius", "Mabxience Research SL",
    "Fresenius Kabi has held 55% of mAbxience since 2022 (Insud Pharma 45%)",
    paste0(
      "https://mabxience.com/fresenius-kabi-completes-majority-stake-",
      "acquisition-of-mabxience-holding-s-l-significantly-enhancing-",
      "presence-in-high-growth-biopharmaceuticals-market/"
    ),
    "g.samsung-bioepis", "Samsung Bioepis NL B.V.", NA, NA,
    "g.merck-kgaa", "Merck Europe B.V.", NA, NA,
    "g.merck-kgaa", "Merck Serono Europe Limited",
    "Serono acquired by Merck KGaA in 2007", wikipedia("Merck_Serono"),
    "g.merck-kgaa", "Serono Europe Limited",
    "Serono acquired by Merck KGaA in 2007", wikipedia("Merck_Serono"),
    "g.organon", "Organon N.V.",
    "Spun off from Merck & Co. (MSD) in 2021", wikipedia("Organon_%26_Co."),
    "g.sobi", "Swedish Orphan Biovitrum AB (publ)", NA, NA,
    "g.csl", "CSL Behring GmbH", NA, NA,
    "g.csl", "Seqirus Netherlands B.V.",
    "CSL's influenza vaccines business (Novartis's, bought in 2014-2015)",
    wikipedia("Seqirus"),
    "g.csl", "Vifor France", "Vifor acquired by CSL in 2022",
    wikipedia("Vifor_Pharma"),
    "g.csl", "Novartis Vaccines and Diagnostics S.r.l.",
    paste(
      "Novartis influenza vaccines acquired by CSL (Seqirus) in 2015; all",
      "this holder's medicines are influenza vaccines (its other vaccines,",
      "and the entity, went to GSK)"
    ),
    paste0(
      "https://www.novartis.com/news/media-releases/novartis-completes-",
      "divestiture-influenza-vaccines-business-csl-limited-usd-275-million"
    ),
    "g.recordati", "Recordati Rare Diseases", NA, NA,
    "g.recordati", "Recordati Ireland Ltd", NA, NA,
    "g.recordati", "Recordati Industria Chimica e Farmaceutica S.p.A.", NA,
    NA,
    "g.pierre-fabre", "Pierre Fabre Medicament", NA, NA,
    "g.medac", "medac Gesellschaft für klinische Spezialpräparate mbH",
    NA, NA,
    "g.biogen", "Biogen Netherlands B.V.", NA, NA,
    "g.biogen", "Biogen Idec Ltd", NA, NA,
    "g.otsuka", "Otsuka Pharmaceutical Netherlands B.V.", NA, NA,
    "g.otsuka", "Otsuka Novel Products GmbH", NA, NA,
    "g.otsuka", "Taiho Pharma Netherlands B.V.",
    "Taiho is an Otsuka Holdings company", wikipedia("Taiho_Pharmaceutical"),
    "g.advanz", "Advanz Pharma Limited", NA, NA,
    "g.advanz", "Amdipharm Limited",
    "Amdipharm Mercury acquired by Concordia in 2015, renamed Advanz Pharma",
    wikipedia("Advanz_Pharma"),
    "g.biomarin", "BioMarin International Limited", NA, NA,
    "g.neuraxpharm", "Neuraxpharm Pharmaceuticals S.L.", NA, NA,
    "g.daiichi-sankyo", "Daiichi Sankyo Europe GmbH", NA, NA,
    "g.orion", "Orion Corporation", NA, NA,
    "g.cheplapharm", "CHEPLAPHARM Arzneimittel GmbH", NA, NA,
    "g.cheplapharm", "CHEPLAPHARM Registration GmbH", NA, NA,
    "g.ipsen", "Ipsen Pharma", NA, NA,
    "g.esteve", "Esteve Pharmaceuticals, S.A.", NA, NA,
    "g.incyte", "Incyte Biosciences Distribution B.V.", NA, NA,
    "g.curium", "Curium Pet France", NA, NA,
    "g.curium", "Curium Romania S.R.L.", NA, NA,
    "g.curium", "CIS bio international",
    paste(
      "Part of Curium, formed from IBA Molecular and Mallinckrodt Nuclear",
      "Medicine in 2017"
    ),
    paste0(
      "https://www.essonne.fr/fileadmin/5-cadre_vie_environnement/",
      "Environnement/risques_majeurs/risques_nucleaire/",
      "CLI-Pr%C3%A9sentation_CURIUM_CLI_291118.pdf"
    ),
    "g.menarini", "Menarini International Operations Luxembourg S.A.", NA,
    NA,
    "g.menarini", "A. Menarini International Licensing S.A.", NA, NA,
    "g.menarini", "A. Menarini Industrie Farmaceutiche Riunite s.r.l.", NA,
    NA,
    "g.menarini", "Berlin-Chemie AG", "Acquired by Menarini in 1992",
    "https://www.berlin-chemie.de/en/about-us/company-history.html",
    "g.menarini", "Stemline Therapeutics B.V.",
    "Stemline acquired by Menarini in 2020",
    paste0(
      "https://www.menarini.com/en-us/news/news-detail/",
      "menarini-group-completes-acquisition-of-stemline-therapeutics.html"
    ),
    "g.kyowa-kirin", "Kyowa Kirin Holdings B.V.", NA, NA,
    "g.kyowa-kirin", "Orchard Therapeutics (Netherlands) B.V.",
    "Orchard acquired by Kyowa Kirin in 2024",
    paste0(
      "https://ir.orchard-tx.com/news-releases/news-release-details/",
      "kyowa-kirin-successfully-completes-acquisition-orchard/"
    ),
    "g.abbott", "Abbott Laboratories Ltd.", NA, NA,
    "g.abbott", "Abbott S.r.l.", NA, NA,
    "g.vertex", "Vertex Pharmaceuticals (Ireland) Limited", NA, NA,
    "g.almirall", "Almirall, S.A.", NA, NA,
    "g.lundbeck", "H. Lundbeck A/S", NA, NA,
    "g.leo-pharma", "LEO Pharma A/S", NA, NA,
    "g.leo-pharma", "LEO Laboratories Ltd.", NA, NA,
    "g.grunenthal", "Grünenthal GmbH", NA, NA,
    "g.theramex", "Theramex Ireland Limited", NA, NA,
    "g.eisai", "Eisai GmbH", NA, NA,
    "g.jazz", "Jazz Pharmaceuticals Ireland Limited", NA, NA,
    "g.jazz", "Gentium S.r.l.", "Gentium acquired by Jazz in 2014",
    paste0(
      "https://investor.jazzpharma.com/news-releases/news-release-details/",
      "jazz-pharmaceuticals-plc-completes-tender-offer-gentium-spa"
    ),
    "g.dr-reddys", "Reddy Holding GmbH",
    "A wholly owned subsidiary of Dr. Reddy's (with betapharm)",
    paste0(
      "https://www.indiaratings.co.in/Uploads/Others/Consolidated%20Subs/",
      "List%20of%20Subsidiaries.pdf"
    ),
    "g.dr-reddys", "betapharm Arzneimittel GmbH",
    "Acquired by Dr. Reddy's in 2006",
    paste0(
      "https://www.biospace.com/dr-reddy-s-laboratories-ltd-completes-",
      "acquisition-of-b-betapharm-b-for-480-million-euro"
    ),
    "g.perrigo", "Laboratoire HRA Pharma",
    "HRA Pharma acquired by Perrigo in 2022",
    paste0(
      "https://investor.perrigo.com/",
      "2022-05-02-PERRIGO-COMPLETES-THE-ACQUISITION-OF-HRA-PHARMA"
    ),
    "g.perrigo", "Galpharm Healthcare Ltd.", "Acquired by Perrigo in 2008",
    paste0(
      "https://investor.perrigo.com/",
      "2008-01-09-Perrigo-Acquires-UK-OTC-Store-Brand-Supplier"
    ),
    "g.glenmark", "Glenmark Arzneimittel GmbH", NA, NA,
    "g.glenmark", "Glenmark Pharmaceuticals s.r.o.", NA, NA,
    "g.merz", "Merz Pharmaceuticals GmbH", NA, NA,
    "g.merz", "Merz Therapeutics GmbH", NA, NA,
    "g.acino", "Acino AG", NA, NA,
    "g.acino", "Acino Pharma GmbH", NA, NA,
    "g.dompe", "Dompe' Farmaceutici S.p.A.", NA, NA,
    "g.dompe", "Dompé Biotec S.p.A.", NA, NA,
    "g.bracco", "Bracco Imaging S.p.A.", NA, NA,
    "g.bracco", "Bracco International B.V.", NA, NA,
    "g.cosmo", "Cosmo Technologies Ltd", NA, NA,
    "g.cosmo", "Cassiopea S.p.A.",
    "A Cosmo Pharmaceuticals company (GLEIF: its ultimate parent)",
    "https://search.gleif.org/#/record/8156002F30A40D4B5408",
    "g.pharming", "Pharming Group N.V.", NA, NA,
    "g.pharming", "Pharming Technologies B.V.", NA, NA,
    "g.bristol-myers-squibb-pfizer", "Bristol-Myers Squibb / Pfizer EEIG",
    NA, NA,
    "g.sanofi-bristol-myers-squibb", "Sanofi Pharma Bristol-Myers Squibb",
    paste(
      "Sanofi and Bristol-Myers Squibb's alliance; Bristol-Myers Squibb",
      "returned its rights outside the U.S. to Sanofi from 1 January 2013"
    ),
    paste0(
      "https://www.sec.gov/Archives/edgar/data/14272/",
      "000119312512413254/d419788dex991.htm"
    ),
    "g.sanofi-pasteur-msd", "Sanofi Pasteur MSD, SNC",
    paste(
      "Sanofi Pasteur and MSD's vaccines joint venture, ended on",
      "31 December 2016 (each took back its own vaccines)"
    ),
    paste0(
      "https://www.merck.com/news/sanofi-pasteur-and-merck-confirm-closing-",
      "date-to-end-joint-vaccines-operations-in-europe/"
    ),
    "g.mcm-vaccine", "MCM Vaccine B.V.", NA, NA,
    "g.vifor-fresenius-medical-care",
    "Vifor Fresenius Medical Care Renal Pharma France",
    "Joint company of Vifor (CSL since 2022) and Fresenius Medical Care",
    wikipedia("Vifor_Pharma")
  )
}

# Holders that are spellings or renames of another holder's company, beyond
# what the rules fold.
curated_company_aliases <- function() {
  dplyr::tribble(
    ~holder, ~company_holder, ~note,
    "Chemical Works of Gedeon Richter Plc. (Gedeon Richter Plc.)",
    "Gedeon Richter Plc.", "Long form of the name",
    "Tour Hekla", "Recordati Rare Diseases",
    "An address line (the register names Recordati Rare Diseases)",
    "Zaklady FarmaFarmaceutyczne Polpharma S.Aceutyczne Polpharma S.A.",
    "Zakłady Farmaceutyczne POLPHARMA S.A.", "Garbled in EMA's data",
    "Pasteur Mà¨rieux MSD", "Sanofi Pasteur MSD, SNC",
    "Garbled in EMA's data (Pasteur Mérieux MSD, an earlier name)",
    "Aventis Pasteur MSD", "Sanofi Pasteur MSD, SNC",
    "Renamed Sanofi Pasteur MSD in 2005",
    "INFAI, Institut für biomedizinische Analytik NMR-Imaging GmbH",
    "INFAI GmbH", "INFAI abbreviates the long name",
    "Laboratoires CTRS - Boulogne Billancourt", "Theravia",
    "Laboratoires CTRS renamed Theravia after merging with Addmedica",
    "Mitsubishi Tanabe Pharma GmbH", "Tanabe Pharma GmbH",
    paste(
      "Mitsubishi Tanabe Pharma and its companies renamed Tanabe Pharma on",
      "1 December 2025"
    ),
    "L. Molteni & C. dei F.lli Alitti Società di .Esercizio .S.p.A",
    "L. Molteni & C. dei Fratelli Alitti Società di Esercizio S.p.A.",
    "Abbreviated and garbled in the Union Register",
    "Gentium S.r.I.", "Gentium S.r.l.", "Misspelt in the Union Register",
    "Steba Biotech B.A.", "STEBA Biotech S.A", "Misspelt in the Union Register",
    "Alimentarics B.V.", "Alimenterics B.V.", "Misspelt in one source",
    "Novartis Ophtalmics Europe Ltd", "Novartis Ophthalmics Europe Ltd.",
    "Misspelt in the Union Register",
    "Archie Samiel s.r.o.", "Archie Samuel s.r.o.", "Misspelt in EMA's data",
    "Laboratoires BIOGARAN", "Biogaran", "Long form of the name",
    "A.C.O.M. -ADVANCED CENTER ONCOLOGY MACERATA -S.R.L.",
    "A.C.O.M. - Advanced Center Oncology", "Long form of the name",
    "Rilonacept FGK Representative Service GmbH",
    "FGK Representative Service GmbH", "Product name prefixed",
    "Takeda Europe R&D Centre Ltd",
    "Takeda Global Research and Development Centre (Europe)", "Renamed",
    "BeiGene Ireland Ltd", "BeOne Medicines Ireland Limited",
    "BeiGene renamed BeOne Medicines in 2025",
    "Ascendis Pharma Bone Diseases A/S",
    "Ascendis Pharma Endocrinology Division A/S", "Two entities, one company",
    "JensonR+ Limited", "Jenson Pharmaceutical Services Limited",
    "Renamed"
  )
}

# Regulatory service firms that hold marketing authorisations for other
# sponsors: their medicines are "held via a regulatory representative"
# until curated_medicine_sponsors() names the sponsor.
curated_representatives <- function() {
  dplyr::tribble(
    ~holder,
    "FGK Representative Service GmbH",
    "Regulatory Pharma Net S.r.l.",
    "Norpharm Regulatory Services Ltd",
    "DLRC Pharma Services Ltd",
    "Guidehouse Germany GmbH",
    "CATS Consultants GmbH",
    "ERA Consulting GmbH",
    "Triskel EU Services Ltd",
    "YES Pharmaceutical Development Services GmbH",
    "Pharm Research Associates (UK) Limited",
    "Jenson Pharmaceutical Services Limited",
    "TMC Pharma Services Ltd",
    "Integral Pharma Solutions EU Limited",
    "Sciencepharma Sp. z o.o"
  )
}

# The sponsor behind a medicine held by a regulatory representative, looked
# up by hand in the medicine's EPAR documents or product information (or a
# company press release): the evidence URL, a quote of at most 20 words
# and the date checked. Only rows a second, independent check confirmed
# (reviewed) are applied. sponsor_group_key: a curated group, or NA for the
# sponsor's own group.
curated_medicine_sponsors <- function() {
  dplyr::tibble(
    ema_product_number = character(),
    holder = character(),
    sponsor = character(),
    sponsor_group_key = character(),
    evidence_url = character(),
    evidence_quote = character(),
    checked_date = as.Date(character()),
    reviewed = logical()
  )
}
